# .github/workflows/ci.yml
#

name: ci
 
on:

  pull_request:

    branches:

      - main

  push:

    branches:

      - main
 
jobs:

  lint:

    name: ESLint

    runs-on: ubuntu-latest

    defaults:

      run:

        working-directory: Assignment1/fragments  # 👈 updated path

    steps:

      - name: Check out code

        uses: actions/checkout@v4
 
      - name: Setup Node

        uses: actions/setup-node@v4

        with:

          node-version: 'lts/*'

          cache: 'npm'

          cache-dependency-path: Assignment1/fragments/package-lock.json  # 👈 updated path
 
      - name: Install node dependencies

        run: npm ci
 
      - name: Run ESLint

        run: npm run lint
 
  unit-tests:

    name: Unit Tests

    runs-on: ubuntu-latest

    defaults:

      run:

        working-directory: Assignment1/fragments  # 👈 same here

    steps:

      - name: Check out code

        uses: actions/checkout@v4
 
      - name: Setup Node

        uses: actions/setup-node@v4

        with:

          node-version: 'lts/*'

          cache: 'npm'

          cache-dependency-path: Assignment1/fragments/package-lock.json
 
      - name: Install node dependencies and run Tests

        run: npm install-ci-test

 