name: ci

on:
  push:
    branches: [ main ]
    paths: [ 'Lab3/**', '.github/workflows/ci.yml' ]
  pull_request:
    branches: [ main ]
    paths: [ 'Lab3/**', '.github/workflows/ci.yml' ]
  workflow_dispatch:

defaults:
  run:
    working-directory: Lab3

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: npm
          cache-dependency-path: 'Lab3/package-lock.json'  # hopefully it works !

      - name: Install node dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint
